from manim import *
class semiCiricle(Scene):
    def construct(self):
        semi = Arc(angle = PI, color = GREEN).set_fill(color = GREEN, opacity = 0.5).scale(3)
        a = semi.point_from_proportion(0)
        b = semi.point_from_proportion(1)
        lab = Line(a, b, color = GREEN)
        self.add(semi, lab)
        self.play(DrawBorderThenFill(semi), Create(lab))
        self.wait()
        vt = ValueTracker(0.1)
        c = always_redraw(lambda: Dot(semi.point_from_proportion(vt.get_value()), color = BLUE))
        lac = always_redraw(lambda: Line(a, c, color = TEAL))
        lbc = always_redraw(lambda: Line(b, c, color = TEAL))
        angle = always_redraw(lambda: Angle(lbc, lac, radius = 0.5, quadrant = (-1,-1)))
        angle_t = always_redraw(lambda: MathTex(r"90.00^\circ").next_to(angle, DOWN))
        self.add(c, lac, lbc, angle, angle_t)
        self.play(vt.animate.set_value(0.9), run_time = 5)
        self.wait()
        self.remove(c, lab, lac, lbc, angle, angle_t)
        self.play(semi.animate.scale(0.75).shift(UP))
        self.wait()
        duplicate = semi.copy()
        self.play(duplicate.animate.rotate(PI).shift(DOWN*2.25))
        self.wait() 